export const SOLICITAR_TOKEN = "SOLICITAR_TOKEN";
export const SOLICITAR_TOKEN_EXITO = "SOLICITAR_TOKEN_EXITO";
export const SOLICITAR_TOKEN_ERROR = "SOLICITAR_TOKEN_ERROR";
export const ELIMINAR_TOKEN = "ELIMINAR_TOKEN";
